#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/add_outer_walls_to_mine_area.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
fill ~-21 ~ ~-21 ~21 ~4 ~-21 glass
fill ~-21 ~ ~21 ~21 ~4 ~21 glass
fill ~-21 ~ ~-21 ~-21 ~4 ~21 glass
fill ~21 ~ ~-21 ~21 ~4 ~21 glass