#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/add_ceiling.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript

fill ~-40 6 ~-40 ~40 6 ~40 glass replace stone
fill ~-40 6 ~-40 ~40 6 ~40 glass replace bedrock
fill ~-40 6 ~-40 ~40 6 ~40 glass replace diorite
fill ~-40 6 ~-40 ~40 6 ~40 glass replace andesite
fill ~-40 6 ~-40 ~40 6 ~40 glass replace granite
fill ~-40 6 ~-40 ~40 6 ~40 glass replace dirt
fill ~-40 6 ~-40 ~40 6 ~40 glass replace gravel
fill ~-40 6 ~-40 ~40 6 ~40 glass replace sand
fill ~-40 6 ~-40 ~40 6 ~40 glass replace lava
fill ~-40 6 ~-40 ~40 6 ~40 glass replace water
fill ~-40 11 ~-40 ~40 11 ~40 glass replace stone
fill ~-40 11 ~-40 ~40 11 ~40 glass replace bedrock
fill ~-40 11 ~-40 ~40 11 ~40 glass replace diorite
fill ~-40 11 ~-40 ~40 11 ~40 glass replace andesite
fill ~-40 11 ~-40 ~40 11 ~40 glass replace granite
fill ~-40 11 ~-40 ~40 11 ~40 glass replace dirt
fill ~-40 11 ~-40 ~40 11 ~40 glass replace gravel
fill ~-40 11 ~-40 ~40 11 ~40 glass replace sand
fill ~-40 11 ~-40 ~40 11 ~40 glass replace lava
fill ~-40 11 ~-40 ~40 11 ~40 glass replace water
fill ~-40 16 ~-40 ~40 16 ~40 glass replace stone
fill ~-40 16 ~-40 ~40 16 ~40 glass replace bedrock
fill ~-40 16 ~-40 ~40 16 ~40 glass replace diorite
fill ~-40 16 ~-40 ~40 16 ~40 glass replace andesite
fill ~-40 16 ~-40 ~40 16 ~40 glass replace granite
fill ~-40 16 ~-40 ~40 16 ~40 glass replace dirt
fill ~-40 16 ~-40 ~40 16 ~40 glass replace gravel
fill ~-40 16 ~-40 ~40 16 ~40 glass replace sand
fill ~-40 16 ~-40 ~40 16 ~40 glass replace lava
fill ~-40 16 ~-40 ~40 16 ~40 glass replace water