#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/add_item_elevator_detector.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
fill ~1 ~1 ~-1 ~1 ~1 ~-1 minecraft:glass
fill ~-1 ~2 ~-2 ~1 ~3 ~-1 minecraft:oak_planks
fill ~1 ~2 ~-1 ~1 ~2 ~-1 minecraft:comparator[facing=east]
fill ~ ~3 ~-1 ~ ~3 ~-1 minecraft:repeater[facing=east,delay=2]
fill ~-1 ~4 ~-1 ~-1 ~4 ~-1 minecraft:redstone_wire
fill ~-1 ~3 ~-2 ~ ~3 ~-2 minecraft:redstone_wire
fill ~-1 ~2 ~-1 ~-1 ~2 ~-1 minecraft:redstone_wall_torch[facing=west]
fill ~1 ~3 ~-1 ~1 ~3 ~-1 minecraft:redstone_wall_torch[facing=south]