#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/add_ceiling_relative_to_entity.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~6 ~-20 ~20 ~6 ~20 glass replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~11 ~-20 ~20 ~11 ~20 glass replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~16 ~-20 ~20 ~16 ~20 glass replace water