#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/add_item_elevator_downward_upper_level.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
fill ~2 ~2 ~ ~2 ~4 ~ minecraft:iron_bars
fill ~2 ~2 ~-1 ~2 ~3 ~-1 minecraft:cobblestone
fill ~2 ~2 ~-1 ~2 ~2 ~-1 minecraft:dropper[facing=east]
fill ~2 ~2 ~ ~2 ~2 ~ minecraft:hopper[facing=north]
function drh:add_item_elevator_detector