#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/add_ceiling.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript

fill ~-20 6 ~-20 ~20 6 ~20 glass replace stone
fill ~-20 6 ~-20 ~20 6 ~20 glass replace bedrock
fill ~-20 6 ~-20 ~20 6 ~20 glass replace diorite
fill ~-20 6 ~-20 ~20 6 ~20 glass replace andesite
fill ~-20 6 ~-20 ~20 6 ~20 glass replace granite
fill ~-20 6 ~-20 ~20 6 ~20 glass replace dirt
fill ~-20 6 ~-20 ~20 6 ~20 glass replace gravel
fill ~-20 6 ~-20 ~20 6 ~20 glass replace sand
fill ~-20 6 ~-20 ~20 6 ~20 glass replace lava
fill ~-20 6 ~-20 ~20 6 ~20 glass replace water
fill ~-20 11 ~-20 ~20 11 ~20 glass replace stone
fill ~-20 11 ~-20 ~20 11 ~20 glass replace bedrock
fill ~-20 11 ~-20 ~20 11 ~20 glass replace diorite
fill ~-20 11 ~-20 ~20 11 ~20 glass replace andesite
fill ~-20 11 ~-20 ~20 11 ~20 glass replace granite
fill ~-20 11 ~-20 ~20 11 ~20 glass replace dirt
fill ~-20 11 ~-20 ~20 11 ~20 glass replace gravel
fill ~-20 11 ~-20 ~20 11 ~20 glass replace sand
fill ~-20 11 ~-20 ~20 11 ~20 glass replace lava
fill ~-20 11 ~-20 ~20 11 ~20 glass replace water
fill ~-20 16 ~-20 ~20 16 ~20 glass replace stone
fill ~-20 16 ~-20 ~20 16 ~20 glass replace bedrock
fill ~-20 16 ~-20 ~20 16 ~20 glass replace diorite
fill ~-20 16 ~-20 ~20 16 ~20 glass replace andesite
fill ~-20 16 ~-20 ~20 16 ~20 glass replace granite
fill ~-20 16 ~-20 ~20 16 ~20 glass replace dirt
fill ~-20 16 ~-20 ~20 16 ~20 glass replace gravel
fill ~-20 16 ~-20 ~20 16 ~20 glass replace sand
fill ~-20 16 ~-20 ~20 16 ~20 glass replace lava
fill ~-20 16 ~-20 ~20 16 ~20 glass replace water