#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/build_room.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say  DEBUG build_room
function drh:build_room_common
fill ~-1 ~-1 ~ ~-1 ~-1 ~2 minecraft:cobblestone
fill ~-1 ~2 ~ ~-1 ~4 ~2 minecraft:cobblestone_wall
fill ~-1 ~ ~ ~-1 ~ ~2 minecraft:oak_door[facing=west,half=lower]
fill ~-1 ~1 ~ ~-1 ~1 ~2 minecraft:oak_door[facing=west,half=upper]
fill ~1 ~-1 ~-2 ~1 ~4 ~-2 minecraft:glass
fill ~2 ~-1 ~-1 ~2 ~4 ~-1 minecraft:glass
fill ~2 ~2 ~-1 ~2 ~2 ~-1 minecraft:dropper[facing=north]
function drh:add_item_elevator_detector