#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/build_elevators_and_penthouse.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
function drh:build_room_common
fill ~2 2 ~-2 ~2 2 ~-2 minecraft:soul_sand
fill ~1 ~-1 ~-2 ~1 ~4 ~-2 minecraft:glass
fill ~2 ~-1 ~-1 ~2 ~4 ~-1 minecraft:glass
fill ~2 ~2 ~-1 ~2 ~2 ~-1 minecraft:dropper[facing=north]
fill ~-3 ~4 ~-3 ~3 ~6 ~-1 minecraft:glass hollow
fill ~-2 ~4 ~-2 ~-2 ~4 ~-2 minecraft:hopper
fill ~-3 ~4 ~-2 ~-3 ~4 ~-2 minecraft:comparator[facing=east]
fill ~-4 ~4 ~-3 ~-4 ~4 ~-1 minecraft:redstone_lamp
fill ~-4 ~3 ~-2 ~-4 ~5 ~-2 minecraft:redstone_lamp
fill ~-5 ~4 ~-2 ~-5 ~4 ~-2 minecraft:bell
fill ~-2 ~3 ~-2 ~-2 ~3 ~-2 minecraft:chest[facing=south]
fill ~2 3 ~-2 ~2 ~5 ~-2 minecraft:water
function drh:add_item_elevator_detector
fill ~-2 3 ~ ~-2 ~-1 ~2 minecraft:water
fill ~-2 2 ~ ~-2 2 ~ minecraft:soul_sand
fill ~-2 2 ~2 ~-2 2 ~2 minecraft:magma_block
fill ~-2 2 ~-1 ~-2 ~-1 ~-1 minecraft:glass
fill ~-2 2 ~-2 ~-2 ~1 ~-2 minecraft:ladder[facing=east]