#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/build_room.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say  DEBUG build_room
fill ~-4 ~ ~-4 ~4 ~4 ~4 minecraft:air
fill ~-4 ~-1 ~-4 ~4 ~-1 ~4 minecraft:glowstone
fill ~-3 ~-1 ~-4 ~3 ~-1 ~4 minecraft:glass
fill ~-4 ~-1 ~-3 ~4 ~-1 ~3 minecraft:glass
fill ~-3 ~-1 ~-3 ~3 ~4 ~3 minecraft:glass hollow
fill ~-1 ~-1 ~ ~-1 ~-1 ~2 minecraft:cobblestone
fill ~-1 ~2 ~ ~-1 ~3 ~2 minecraft:iron_bars
fill ~-1 ~ ~ ~-1 ~ ~2 minecraft:oak_door[facing=west,half=lower]
fill ~-1 ~1 ~ ~-1 ~1 ~2 minecraft:oak_door[facing=west,half=upper]