#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/bump_miner_entity_OLD.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say bump_miner_entity beginning

say bump_miner_entity DONE