#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_non_ores2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say  DEBUG excavate_non_ores2
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace gravel
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace sand