#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_relative_to_entity.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~5 ~40 air replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~2 ~-40 ~40 ~2 ~40 torch replace air
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~10 ~40 air replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~7 ~-40 ~40 ~7 ~40 torch replace air
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~15 ~40 air replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-40 ~12 ~-40 ~40 ~12 ~40 torch replace air