#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript


fill ~-20 2 ~-20 ~20 5 ~20 air replace stone
fill ~-20 2 ~-20 ~20 5 ~20 air replace bedrock
fill ~-20 2 ~-20 ~20 5 ~20 air replace diorite
fill ~-20 2 ~-20 ~20 5 ~20 air replace andesite
fill ~-20 2 ~-20 ~20 5 ~20 air replace granite
fill ~-20 2 ~-20 ~20 5 ~20 air replace dirt
fill ~-20 2 ~-20 ~20 5 ~20 air replace gravel
fill ~-20 2 ~-20 ~20 5 ~20 air replace gravel
fill ~-20 2 ~-20 ~20 5 ~20 air replace gravel
fill ~-20 2 ~-20 ~20 5 ~20 air replace gravel
fill ~-20 2 ~-20 ~20 5 ~20 air replace sand
fill ~-20 2 ~-20 ~20 5 ~20 air replace sand
fill ~-20 2 ~-20 ~20 5 ~20 air replace sand
fill ~-20 2 ~-20 ~20 5 ~20 air replace sand
fill ~-20 2 ~-20 ~20 5 ~20 air replace lava
fill ~-20 2 ~-20 ~20 5 ~20 air replace water
fill ~-20 2 ~-20 ~20 2 ~20 torch replace air
fill ~-20 7 ~-20 ~20 10 ~20 air replace stone
fill ~-20 7 ~-20 ~20 10 ~20 air replace bedrock
fill ~-20 7 ~-20 ~20 10 ~20 air replace diorite
fill ~-20 7 ~-20 ~20 10 ~20 air replace andesite
fill ~-20 7 ~-20 ~20 10 ~20 air replace granite
fill ~-20 7 ~-20 ~20 10 ~20 air replace dirt
fill ~-20 7 ~-20 ~20 10 ~20 air replace gravel
fill ~-20 7 ~-20 ~20 10 ~20 air replace gravel
fill ~-20 7 ~-20 ~20 10 ~20 air replace gravel
fill ~-20 7 ~-20 ~20 10 ~20 air replace gravel
fill ~-20 7 ~-20 ~20 10 ~20 air replace sand
fill ~-20 7 ~-20 ~20 10 ~20 air replace sand
fill ~-20 7 ~-20 ~20 10 ~20 air replace sand
fill ~-20 7 ~-20 ~20 10 ~20 air replace sand
fill ~-20 7 ~-20 ~20 10 ~20 air replace lava
fill ~-20 7 ~-20 ~20 10 ~20 air replace water
fill ~-20 7 ~-20 ~20 7 ~20 torch replace air
fill ~-20 12 ~-20 ~20 15 ~20 air replace stone
fill ~-20 12 ~-20 ~20 15 ~20 air replace bedrock
fill ~-20 12 ~-20 ~20 15 ~20 air replace diorite
fill ~-20 12 ~-20 ~20 15 ~20 air replace andesite
fill ~-20 12 ~-20 ~20 15 ~20 air replace granite
fill ~-20 12 ~-20 ~20 15 ~20 air replace dirt
fill ~-20 12 ~-20 ~20 15 ~20 air replace gravel
fill ~-20 12 ~-20 ~20 15 ~20 air replace gravel
fill ~-20 12 ~-20 ~20 15 ~20 air replace gravel
fill ~-20 12 ~-20 ~20 15 ~20 air replace gravel
fill ~-20 12 ~-20 ~20 15 ~20 air replace sand
fill ~-20 12 ~-20 ~20 15 ~20 air replace sand
fill ~-20 12 ~-20 ~20 15 ~20 air replace sand
fill ~-20 12 ~-20 ~20 15 ~20 air replace sand
fill ~-20 12 ~-20 ~20 15 ~20 air replace lava
fill ~-20 12 ~-20 ~20 15 ~20 air replace water
fill ~-20 12 ~-20 ~20 12 ~20 torch replace air