#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_floor.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say  DEBUG excavate_floor
function drh:build_room
function drh:prep_next_room