#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_relative_to_entity.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~5 ~20 air replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~2 ~-20 ~20 ~2 ~20 torch replace air
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~10 ~20 air replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~7 ~-20 ~20 ~7 ~20 torch replace air
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace stone
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace bedrock
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace diorite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace andesite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace granite
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace dirt
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace gravel
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace sand
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace lava
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~15 ~20 air replace water
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-20 ~12 ~-20 ~20 ~12 ~20 torch replace air