#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavators_delete.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
kill @e[type=chest_minecart,name=Excavator]