#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_floor.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
tellraw @a ["",{"text":"** Excavationg for level "},{"score":{"name":"@e[type=chest_minecart,name=Excavator,limit=1]","objective":"y"}},{"text":" **"}]
function drh:build_room
function drh:get_excavator_pos
function drh:floor_indicator_add
function drh:add_outer_walls_to_mine_area
function drh:excavate_non_ores1
function drh:excavate_non_ores2
function drh:excavate_non_ores3
function drh:prep_next_room