#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_non_ores3.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace lava
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace water
fill ~-20 ~5 ~-20 ~20 ~5 ~20 glass replace lava
fill ~-20 ~5 ~-20 ~20 ~5 ~20 glass replace water
fill ~-20 ~5 ~-20 ~20 ~5 ~20 glass replace stone
fill ~-20 ~5 ~-20 ~20 ~5 ~20 glass replace air