#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_non_ores1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace bedrock
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace stone
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace diorite
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace andesite
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace granite
fill ~-20 ~ ~-20 ~20 ~4 ~20 air replace dirt