#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/excavate_init.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say  DEBUG excavate_init
function drh:sidebar_show_y
function drh:get_player_pos
function drh:excavators_delete
function drh:init_excavator_and_chamber
function drh:get_player_pos
function drh:get_excavator_pos