#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/floor_counter_increment.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
scoreboard players add y_color_value y_color_value 1
execute if score y_color_value y_color_value matches 16.. run scoreboard players set y_color_value y_color_value 0
