#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/floor_indicator_add.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
fill ~-2 ~ ~1 ~-2 ~ ~1 minecraft:air
fill ~-3 ~ ~1 ~-3 ~ ~1 minecraft:cobblestone
fill ~-2 ~ ~1 ~-2 ~ ~1 minecraft:oak_wall_sign[facing=east]{CustomName:"LevelIndicator",Text1:'"Y is:"',Text2:'{"score":{"name":"@e[type=chest_minecart,name=Excavator,limit=1]","objective":"y"}}'}