#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function drh:mcscript/load


function drh:sidebar_clear
say  ------------




say  DEBUG xz_delta: 20










