#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function drh:mcscript/load


function drh:sidebar_clear
say -- Mining utilities loaded! --
say -- Go to the top of something and enter this command: `function excavate` --




















