#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/prep_mine_new.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say prep_mine_new beginning

scoreboard objectives setdisplay sidebar y
execute store result score @s y run data get entity @s Pos[1]
function drh:add_ceiling
function drh:excavate
fill ~-1 16 ~-1 ~1 18 ~1 glass hollow
summon chest_minecart ~ 17 ~ {CustomName:"\"Foo\""}
function drh:start_miner_entity
say TODO: /kill @e[type=chest_minecart,name=Foo]
function drh:tunnel_down
say prep_mine_new DONE