#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/prep_mine.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say start
function drh:add_ceiling
function drh:excavate
say done