#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/prep_next_room.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say  DEBUG prep_next_room
fill ~-4 ~3 ~-4 ~4 ~9 ~4 minecraft:air
fill ~-4 ~4 ~-4 ~4 ~4 ~4 minecraft:glowstone
fill ~-3 ~4 ~-4 ~3 ~4 ~4 minecraft:glass
fill ~-4 ~4 ~-3 ~4 ~4 ~3 minecraft:glass
fill ~-3 ~4 ~-3 ~3 ~9 ~3 minecraft:glass hollow
tp @e[type=chest_minecart,name=Excavator,limit=1] ~ ~5 ~
function drh:get_excavator_pos