#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/sidebar_clear.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
scoreboard objectives setdisplay sidebar clear_sidebar