#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/start_miner_entity.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
say start_miner_entity beginning

execute store result score @e[type=chest_minecart,name=Foo,limit=1] y run data get entity @e[type=chest_minecart,name=Foo,limit=1] Pos[1]
function drh:bump_miner_entity
say start_miner_entity DONE