#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/test2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript

say 121



execute store result score @s x run data get entity @s Pos[0]
execute store result score @s y run data get entity @s Pos[1]
execute store result score @s z run data get entity @s Pos[2]
scoreboard objectives setdisplay sidebar y
scoreboard players set @s y 5
scoreboard objectives list
scoreboard players list
summon chest_minecart ~ ~ ~ {CustomName:'{"text":"Menu!"}'}