#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/test4.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
scoreboard players set @s score 2
execute if score @s matches 0.. run say score is positive
execute if score @s matches 0.. run say multi line
