#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/test2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
scoreboard players set test_val test_val 2
function drh:test3
scoreboard players add test_val test_val 1
function drh:test3
scoreboard players add test_val test_val 1
function drh:test3
scoreboard players add test_val test_val 1
function drh:test3
scoreboard players add test_val test_val 1
function drh:test3
scoreboard players add test_val test_val 1