#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/test3.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
execute if score test_val test_val matches 0 if entity @s[tag=!mcscriptSwitch] run say var is 0
execute if score test_val test_val matches 0 if entity @s[tag=!mcscriptSwitch] run tag @s add mcscriptSwitch
execute if score test_val test_val matches 1 if entity @s[tag=!mcscriptSwitch] run say var is 1
execute if score test_val test_val matches 1 if entity @s[tag=!mcscriptSwitch] run tag @s add mcscriptSwitch
execute if score test_val test_val matches 2 if entity @s[tag=!mcscriptSwitch] run say var is 2
execute if score test_val test_val matches 2 if entity @s[tag=!mcscriptSwitch] run tag @s add mcscriptSwitch
execute if score test_val test_val matches 5.. if entity @s[tag=!mcscriptSwitch] run say var is over 4
execute if score test_val test_val matches 5.. if entity @s[tag=!mcscriptSwitch] run tag @s add mcscriptSwitch
execute if score test_val test_val matches ..1 if entity @s[tag=!mcscriptSwitch] run say var is below 2
execute if score test_val test_val matches ..1 if entity @s[tag=!mcscriptSwitch] run tag @s add mcscriptSwitch
execute if entity @s[tag=!mcscriptSwitch] run say SORRY no match
tag @s remove mcscriptSwitch