#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/tunnel_down.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# this file is generated based on a function specified in.//drh/data/drh/functions/load.mcscript
fill ~-1 2 ~-1 ~1 ~2 ~1 glass hollow
fill ~ 2 ~ ~ ~2 ~ minecraft:ladder
fill ~1 2 ~1 ~1 ~2 ~1 minecraft:glowstone