#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
#ler!
scoreboard objectives add clear_sidebar dummy
scoreboard objectives add y dummy
