#######
# Compiled from data/drh/functions/load.mcscript
# to .//drh/data/drh/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######

# Extended from data/drh/functions/load.mcscript
# to drh/data/drh/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add clear_sidebar dummy
scoreboard objectives add y dummy
