#######
# Compiled from data/drh/functions/load.mcscript
# to drh/data/drh/functions/mcscript/while1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=chest_minecart,name=Excavator,limit=1] at @s run function drh:excavate_floor
execute if entity @s[tag=!mcscriptStop] if score @e[type=chest_minecart,name=Excavator,limit=1] y < @s y run function drh:mcscript/while1
tag @s[tag=mcscriptStop] remove mcscriptStop
