#######
# Compiled from data/drh/functions/load.mcscript
# to drh/data/drh/functions/mcscript/while1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say prep_mine_new next
function drh:add_ceiling_relative_to_entity
function drh:excavate_relative_to_entity
execute as @e[type=chest_minecart,name=Foo,limit=1] run fill ~-1 ~14 ~-1 ~1 ~16 ~1 glass hollow
tp @e[type=chest_minecart,name=Foo.limit=1] ~ ~15 ~
execute store result score @e[type=chest_minecart,name=Foo,limit=1] y run data get entity @e[type=chest_minecart,name=Foo,limit=1] Pos[1]
execute if entity @s[tag=!mcscriptStop] if score @e[type=chest_minecart,name=Foo,limit=1] y < @s y run function drh:mcscript/while1
tag @s[tag=mcscriptStop] remove mcscriptStop
