#######
# Compiled from data/drh/functions/load.mcscript
# to drh/data/drh/functions/mcscript/while3.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @s dz NaN
execute if score dz dz matches ..20 run function drh:mcscript/while4
scoreboard players add @s dx 4
execute if entity @s[tag=!mcscriptStop] if score dx dx matches ..20 run function drh:mcscript/while3
tag @s[tag=mcscriptStop] remove mcscriptStop
