#######
# Compiled from data/drh/functions/load.mcscript
# to drh/data/drh/functions/mcscript/while6.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say fill ~$(dx) ~undefined ~dz ~$(dx) ~undefined ~$(dz) torch replace air
fill ~$(dx) ~undefined ~$(dz) ~$(dx) ~undefined ~$(dz) torch replace air
scoreboard players add @s dz 4
execute if entity @s[tag=!mcscriptStop] if score dz dz matches ..20 run function drh:mcscript/while6
tag @s[tag=mcscriptStop] remove mcscriptStop
