#######
# Compiled from data/drh/functions/load.mcscript
# to drh/data/drh/functions/mcscript/while1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say bump_miner_entity_NEXT
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run function drh:add_ceiling_relative_to_entity
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run function drh:excavate_relative_to_entity
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run fill ~-1 ~14 ~-1 ~1 ~16 ~1 glass hollow
execute as @e[type=chest_minecart,name=Foo,limit=1] at @s run tp @e[type=chest_minecart,name=Foo,limit=1] ~ ~15 ~
execute store result score @e[type=chest_minecart,name=Foo,limit=1] y run data get entity @e[type=chest_minecart,name=Foo,limit=1] Pos[1]
say TODO drh:bump_miner_entity re-loop
execute if entity @s[tag=!mcscriptStop] if score @e[type=chest_minecart,name=Foo,limit=1] y < @s y run function drh:mcscript/while1
tag @s[tag=mcscriptStop] remove mcscriptStop
